# Generated by Django 6.0.4 on 2026-04-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factionmember',
            name='role',
            field=models.CharField(choices=[('leader', 'Лидер'), ('officer', 'Офицер'), ('member', 'Участник'), ('recruit', 'Новичок'), ('guest', 'Гость')], default='member', max_length=20),
        ),
    ]
